/* eslint-disable @typescript-eslint/ban-ts-comment */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Providers from "@/redux/features/Providers";
import AppInitializer from "@/components/AppInitializer/AppInitializer";
import { Toaster } from "sonner";

const arial = Geist({
  variable: "--font-arial",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cast Link AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${arial.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster position='top-right' />
          <AppInitializer>
            <Navbar />
            {children}
            <Footer />
          </AppInitializer>
        </Providers>
      </body>
    </html>
  );
}
