/* eslint-disable @typescript-eslint/ban-ts-comment */

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// @ts-ignore
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Providers from "@/redux/features/Providers";
import AppInitializer from "@/components/AppInitializer/AppInitializer";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import CookieBanner from "@/components/shared/CookieBanner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cast Link AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <TooltipProvider>
            <Toaster position='top-right' />
            <AppInitializer>
              <Navbar />
              {children}
              <Footer />
              <CookieBanner />
            </AppInitializer>
          </TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
